martin:
  general:
    SCREENSHOTS_DIR: "chat_screenshots"
    BASE_IMAGE: "base_image.png"
    CHECK_INTERVAL: 3
    DEFAULT_CHAT_DATA_FILE: "dialog_info/chat_data.csv"
    KEYWORD: "@马丁"
    USER_PROMPT_TEMPLATE: |
      chat_history: [{chat_history}],
      query: {query}
    LLM: "glm-4.7"
    STICKERS_DIR: "stickers"

  # 视觉模块
  vision:
    DIFFERENCE_THRESHOLD: 1099
    CHECK_INTERVAL: 3
    SAVE_IMAGES: true
    DEFAULT_API_KEY: "your-zhipu-api-key"
    DEFAULT_SYSTEM_PROMPT_FILE: "default_prompt_files/vlm/system_prompt.txt"
    DEFAULT_USER_PROMPT_FILE: "default_prompt_files/vlm/user_prompt.md"
    DEFAULT_MODEL: "glm-4.6v-flash"

  # 核心模块
  core:
    sliding_window_size: 15
    repetition_check_area: 9
  
  # 认知模块
  mind:
    MARTIN_IDENTITIES_TABLE: "default_prompt_files/llm/martin_identities_365.csv"
    YEAR: 2026
    DEFAULT_API_KEY: "your-zhipu-api-key"
    DEFAULT_SYSTEM_PROMPT_TEMPLATE: "default_prompt_files/llm/system_prompt_template.md"
    DEFAULT_MODEL: "glm-4.7-flash"
  
  # 操作模块
  claw:
    click_count: 2
    click_interval: 0.25
  
  # 装备模块
  equipments:
    LOG_LEVEL: INFO
    LOG_FILE: "logs/martin.log"
    COORDINATES_FILE: "mouse_coordinates.json"
  
  # 技能模块
  skills:
    FIRECRAWL_API_KEY: "your-firecrawl-api-key"
    DB_URL: "sqlite:///martin_tasks.db"
